"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

[package]
disabled = true
symbol = ""
format = "via [$symbol $version](bold purple) "

[fill]
symbol = " "

[shell]
disabled = false
bash_indicator = " "
style = "bold #FFFFE3"
format = "[$bash_indicator]($style)"

[character]
success_symbol = "[➜](bold #06D6A0)"
error_symbol = "[✗](bold #FF746C)"

[username]
style_user = "bold #F20CB1"
style_root = "bold #F20CB1"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
read_only = "󰌾"
style = "bold #A2D2FF"
format = "[$path]($style)[$read_only]($style) "

[time]
disabled = false
format = " [$time]($style) "
time_format = "%R"
style = "bold #FFFFE3"

[git_branch]
symbol = " "
style = "bold #FFEE8C"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold yellow"
format = "[$all_status$ahead_behind]($style)"
staged = "[staged](#80EF80) "
modified = "[modified](#FF746C) "
untracked = "[untracked](#FFC067) "
deleted = "[-](red) "
conflicted = "[=](bold red) "
renamed = "[»](blue) "
typechanged = "[↺](cyan) "

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"
format = "([+$added]($added_style) [-$deleted]($deleted_style)) "

[lua]
symbol = ""
format = "via [$symbol $version](bold blue) "

[rust]
symbol = ""
format = "via [$symbol $version](bold red) "

[java]
symbol = ""
format = "via [$symbol $version](bold brown) "

[kotlin]
symbol = ""
format = "via [$symbol $version](bold purple) "

[python]
symbol = " "
pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[nodejs]
format = "via [ Node.js $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[php]
symbol = ""
format = "via [$symbol $version](bold purple) "

[golang]
symbol = ""
format = "via [$symbol $version](bold blue) "

[dart]
symbol = ""
format = "via [$symbol $version](bold blue) "
