# ----- Git config
[git_branch]
symbol = " "
style = "bold #FFEE8C"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold yellow"
format = "[$all_status$ahead_behind]($style)"
staged = "[staged](#80EF80) "
modified = "[modified](#FF746C) "
untracked = "[untracked](#FFC067) "
deleted = "[-](red) "
conflicted = "[=](bold red) "
renamed = "[»](blue) "
typechanged = "[↺](cyan) "

[git_metrics]
disabled = false
added_style = "bold green"
deleted_style = "bold red"
format = "([+$added]($added_style) [-$deleted]($deleted_style)) "

# [git_state]
# style = "bright-black"
# format = '\([$state( $progress_current/$progress_total)]($style)\) '

# [git_commit]
# commit_hash_length = 8
# style = "green"
# only_detached = false
# format = " [$hash]($style)"